theme: jekyll-theme-minimal
title: Rainbow 6 Siege Renown Farming and BP Grinding
description: An LFG server for Rainbow 6 Siege, particularly for users who are farming renown or grinding the Battlepass and Ubisoft challenges.
logo: https://u.cubeupload.com/Exalted/NewFarmLogo.png
show_downloads: false
is_project_page: false
