theme: jekyll-theme-minimal
title: Rainbow 6 Siege Renown Farming and BP Grinding
description: A Discord community of Rainbow 6 Siege players and farmers.
logo: https://u.cubeupload.com/Exalted/NewFarmLogo.png
show_downloads: false
